//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diet
    {
        public Diet()
        {
            this.Comments = new HashSet<Comment>();
            this.DietIngredients = new HashSet<DietIngredient>();
            this.DietMeals = new HashSet<DietMeal>();
            this.UserDiets = new HashSet<UserDiet>();
        }
    
        public int Id { get; set; }
        public bool IsPublic { get; set; }
        public string ImgUrl { get; set; }
        public string WebUrl { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsDeleted { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual DietCategory DietCategory { get; set; }
        public virtual ICollection<DietIngredient> DietIngredients { get; set; }
        public virtual ICollection<DietMeal> DietMeals { get; set; }
        public virtual ICollection<UserDiet> UserDiets { get; set; }
    }
}
