//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DietIngredient
    {
        public int DietId { get; set; }
        public int IngredientId { get; set; }
        public double Quantity { get; set; }
        public int QuantityTypeId { get; set; }
        public string Day { get; set; }
        public int Time { get; set; }
    
        public virtual Diet Diet { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual QuantityType QuantityType { get; set; }
    }
}
