//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessRecipiesEntities : DbContext
    {
        public FitnessRecipiesEntities()
            : base("name=FitnessRecipiesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<Diet> Diets { get; set; }
        public DbSet<Ingredient> Ingredients { get; set; }
        public DbSet<Meal> Meals { get; set; }
        public DbSet<MealIngredient> MealIngredients { get; set; }
        public DbSet<QuantityType> QuantityTypes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<MealCategory> MealCategories { get; set; }
        public DbSet<DietCategory> DietCategories { get; set; }
        public DbSet<IngredientCategory> IngredientCategories { get; set; }
        public DbSet<DietIngredient> DietIngredients { get; set; }
        public DbSet<DietMeal> DietMeals { get; set; }
        public DbSet<Brand> Brands { get; set; }
        public DbSet<Recipe> Recipes { get; set; }
        public DbSet<UserDiet> UserDiets { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<IngredientQuantity> IngredientQuantities { get; set; }
    }
}
