//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public Ingredient()
        {
            this.Ingredient1 = new HashSet<Ingredient>();
            this.MealIngredients = new HashSet<MealIngredient>();
            this.DietIngredients = new HashSet<DietIngredient>();
            this.IngredientQuantities = new HashSet<IngredientQuantity>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public double Carb { get; set; }
        public double Protein { get; set; }
        public double Fat { get; set; }
        public double Kcal { get; set; }
        public Nullable<int> QuantityTypeId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Link { get; set; }
        public Nullable<int> BrandId { get; set; }
    
        public virtual ICollection<Ingredient> Ingredient1 { get; set; }
        public virtual Ingredient Ingredient2 { get; set; }
        public virtual QuantityType QuantityType { get; set; }
        public virtual ICollection<MealIngredient> MealIngredients { get; set; }
        public virtual IngredientCategory IngredientCategory { get; set; }
        public virtual ICollection<DietIngredient> DietIngredients { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<IngredientQuantity> IngredientQuantities { get; set; }
    }
}
