//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientQuantity
    {
        public int IngredientId { get; set; }
        public int QuantitytypeId { get; set; }
        public double To100Ggram { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual QuantityType QuantityType { get; set; }
    }
}
