//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealCategory
    {
        public MealCategory()
        {
            this.Meals = new HashSet<Meal>();
            this.MealCategory1 = new HashSet<MealCategory>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual ICollection<MealCategory> MealCategory1 { get; set; }
        public virtual MealCategory MealCategory2 { get; set; }
    }
}
