//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meal
    {
        public Meal()
        {
            this.MealIngredients = new HashSet<MealIngredient>();
            this.Comments = new HashSet<Comment>();
            this.Users = new HashSet<User>();
            this.DietMeals = new HashSet<DietMeal>();
        }
    
        public int Id { get; set; }
        public string ImgUrl { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int UserId { get; set; }
    
        public virtual ICollection<MealIngredient> MealIngredients { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual MealCategory MealCategory { get; set; }
        public virtual ICollection<DietMeal> DietMeals { get; set; }
        public virtual Recipe Recipe { get; set; }
        public virtual User User { get; set; }
    }
}
