//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessRecipes.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityType
    {
        public QuantityType()
        {
            this.Ingredients = new HashSet<Ingredient>();
            this.MealIngredients = new HashSet<MealIngredient>();
            this.DietIngredients = new HashSet<DietIngredient>();
            this.IngredientQuantities = new HashSet<IngredientQuantity>();
        }
    
        public int Id { get; set; }
        public bool IsDeleted { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Ingredient> Ingredients { get; set; }
        public virtual ICollection<MealIngredient> MealIngredients { get; set; }
        public virtual ICollection<DietIngredient> DietIngredients { get; set; }
        public virtual ICollection<IngredientQuantity> IngredientQuantities { get; set; }
    }
}
